apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - image: dockersamples/examplevotingapp_result
      name: result-app-pod
      ports:
       - containerPort: 80
