apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - image: dockersamples/examplevotingapp_vote
      name: voting-app-pod
      ports:
       - containerPort: 80
         
